import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { NextUiProvider } from "@/providers/nextui.provider";
import { LangProvider } from "@/providers/lang.provider";
import { NavbarSection } from "@/sections/navbar.section";
import { FooterSection } from "@/sections/footer.section";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable}  ${geistMono.variable} antialiased`}
      >
        <NextUiProvider>
          <LangProvider locale={params?.locale}>
            
            {/* navbar */}
            <NavbarSection />

            {/* main */}
            <main className="font-poppins">
              {children}

            </main>

            {/* footer */}
            <FooterSection />

          </LangProvider>

        </NextUiProvider>

      </body>
    </html>
  );
}
