"use client"
// import type { Metadata } from "next";
import { NextUiProvider } from "@/providers/nextui.provider";
import { LangProvider } from "@/providers/lang.provider";
import { FooterSection } from "@/sections/footer.section";
import { useParams } from "next/navigation";
import { AuthentificatedNavbarSection } from "@/sections/authentificated.navbar.section";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default  function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const params = useParams();

  const locale = params.locale;

  return (
      <section
       
      >
        <NextUiProvider>
          <LangProvider locale={locale as string}>
            
            {/* navbar */}
            {/* <NavbarSection /> */}
            <AuthentificatedNavbarSection />

            {/* main */}
            <main className="font-poppins ">
              {children}

            </main>

              {/* <SwitchThemeComponent /> */}

            {/* footer */}
            <FooterSection />

          </LangProvider>

        </NextUiProvider>

      </section>
  );
}
